---
version: '3.8'

services:

  chitchat-db:
    build:
      context: .
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: chitchat
      POSTGRES_PASSWORD: chitchatpass
      POSTGRES_DB: chitchat
